### ISSUE TITLE
unresponsive on chrome 65.0

### ISSUE THREAD

**Issue by cavvia** [arenahq/chrome-extension#13]
Clicking the icon raises this error window in Chrome 65.0. Possibly an AdBlock conflict, not sure. Background console shows no network activity or log info.

![screen shot 2018-03-23 at 12 55 06 pm](https://user-images.githubusercontent.com/64404/37827909-98ec3d36-2e99-11e8-8e53-4e2c125b2cda.png)

**Comment by hxrts** [comment]
hey Anil, couple questions:

- what OS/version are you running?
- also, just to make sure, you tried this on multiple sites? github, for instance, blocks js injection. as a positive control, do you get the same behavior on [nytimes.com](https://www.nytimes.com/)?

**Comment by cavvia** [comment]
Hi Sam - This would be the latest version (0.2.1) on OS X. I think I was testing on Github actually, so that must have been the issue. Seems to work fine on other sites such as nytimes.com.

**Comment by hxrts** [comment]
oh great. glad that worked out. I believe there's an update to the chrome extension / bookmarklet on the team's roadmap, but for now those links blocking injection have to be added via the are.na web interface.
